### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by grifas** [zdaecq/GoogleStaticMapsWrapper#1]
Hi,

Do you think it will be possible to implement the signature of the url ?

**Comment by bonyadmitr** [comment]
Hi. What do you mean?

**Comment by grifas** [comment]
In the Google Documentation : 

> signature (recommended) is a digital signature used to verify that any site generating requests using your API key is authorized to do so. Note: If you enable billing, the digital signature is required. If you exceed the free daily limit of map loads, additional map loads are billable for the remainder of that day. Billable map loads that do not include a digital signature will fail

**Comment by bonyadmitr** [comment]
@grifas 
I think it is possible. Why not?
GoogleStaticMapsWrapper create simple url.
You can see the source. It can be done by any platform. 
Google Documentation recomend to use digital signature.
I didn't use it, but you can try to add one.

https://developers.google.com/maps/documentation/static-maps/get-api-key
